### ISSUE TITLE
Complete Mode: Lower and Upper Bound

### ISSUE THREAD

**Issue by NonlinearFruit** [teinvdlugt/PiTrainer#1]
Complete is a really nice feature, especially since you can enter the upper bound (eg digits 1 through 100). If there was also a field for entering the lower bound, that would allow for more focused practice (eg digits 100 through 200). 

For example, I am currently working on 150 to 200. In Complete mode, any string of digits below 100 is more tedious then helpful. The ideal range for me right now would be 100 to 200.

**Comment by teinvdlugt** [comment]
Already working on it! Thanks.

**Comment by NonlinearFruit** [comment]
:+1: Great update
