### ISSUE TITLE
Practise Mode: Starting Place

### ISSUE THREAD

**Issue by NonlinearFruit** [teinvdlugt/PiTrainer#2]
It would be nice to be able to set where you start and be able to reset to that place (via the reset button). For example, if I start at the 100th digit, go as far as I can, and then click reset to go back to the 100th digit.

**Comment by teinvdlugt** [comment]
Working on it!

**Comment by teinvdlugt** [comment]
Sorry it took so long. The feature has now been released to the beta channel in the Google Play Store and I will soon promote it to the main channel. The updates are in the new-settings branch.
